### ISSUE TITLE
确实有错误在以前用命令行写过 再运行会crash

### ISSUE THREAD

**Issue by huang5556019** [DevDragonLi/XcodePluginUpgrade-LFL#2]
第73行的
`NSDictionary *pluginInfoDictionary = [[NSDictionary alloc] initWithContentsOfFile:pluginPlistPath];`
应该改为
`NSMutableDictionary *pluginInfoDictionary = [[NSMutableDictionary alloc] initWithContentsOfFile:pluginPlistPath];`
因为在下面的判断中你有对不可变字典设置值,导致crash-------------
`if (![supportedUUIDs containsObject:xcodeUUID]) {
                        [supportedUUIDs addObject:xcodeUUID];
                        [pluginInfoDictionary setValue:supportedUUIDs forKey:@"DVTPlugInCompatibilityUUIDs"];
                        [pluginInfoDictionary writeToFile:pluginPlistPath atomically:YES];
                    }`

**Comment by DevDragonLi** [comment]
多谢,已修正
