### ISSUE TITLE
当我的电脑有多个用户的时候运行不成功

### ISSUE THREAD

**Issue by yandeguangzy** [DevDragonLi/XcodePluginUpgrade-LFL#3]
我的电脑有多个用户，它会遍历输出所有用户，但是最后提示是Wrong path,Please try again!
Program ended with exit code: 0。怎么办？

**Comment by DevDragonLi** [comment]
You can locate the code of the user that line, change to your current user name, should be ok, code one line is the output of the current user name, find the changes
